name: CMake on Ubuntu and Windows

on:
  push:
    branches: [ "master", "develop", "prod" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.4.2'
        target: 'desktop'
        set-env: 'true'

    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake Ubuntu
      if: runner.os == 'Linux'
      run: |
        echo "Running Linux build"
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -S ${{ github.workspace }} \
            -G "Unix Makefiles" # Use Unix Makefiles for Ubuntu
      shell: bash  # This makes sure we use Bash on both platforms.

    - name: Configure CMake Windows
      if: runner.os == 'Windows'
      run: |
        echo "Running Windows build"
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -S ${{ github.workspace }} \
            -G "Visual Studio 17 2022"
      shell: pwsh

    - name: Build
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
      shell: bash

    - name: Package Windows Build
      if: runner.os == 'Windows'
      shell: pwsh  # Ensure PowerShell is used here on Windows.
      run: |
        mkdir -p ${{ steps.strings.outputs.build-output-dir }}/installer
        windeployqt ${{ steps.strings.outputs.build-output-dir }}/Tail-Tray.exe --dir ${{ steps.strings.outputs.build-output-dir }}/installer
        zip -r Tail-Tray.zip ${{ steps.strings.outputs.build-output-dir }}/installer

    - name: Package DEB file
      if: runner.os == 'Linux' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod')
      run: |
         chmod +x ./build-deb.sh
         ./build-deb.sh ${{ steps.strings.outputs.build-output-dir }}
      shell: bash

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Dev build artifacts"
        files: |
          ${{ steps.strings.outputs.build-output-dir }}/*.deb
          ${{ steps.strings.outputs.build-output-dir }}/Tail-Tray.zip
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod')
