name: Build Deb for Ubuntu 25.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Create structure
        shell: bash
        run: |
          mkdir -p ${{ steps.strings.outputs.build-output-dir }}
          echo "Build output directory: ${{ steps.strings.outputs.build-output-dir }}"

      - name: Package DEB file for Ubuntu 25.04
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          artifacts-dir: build
          docker-image: ubuntu:25.04
          extra-build-deps: devscripts git libkf6notifications-dev
          before-build-hook: |
            git checkout debian/changelog
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DKNOTIFICATIONS_ENABLED=ON \
              -S /__w/tail-tray/tail-tray \
              -G "Unix Makefiles"
            
            debchange --controlmaint --local="ubuntu-25.04-plucky~git$(git rev-parse --short HEAD)" "CI build"
            buildpackage-opts: --build=binary --no-sign

      - name: Upload DEB files
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          mv ${{ steps.strings.outputs.build-output-dir }}/*ubuntu-25.04*.deb ${{ steps.strings.outputs.build-output-dir }}/tail-tray-ubuntu-25.04.deb
          gh release upload latest ${{ steps.strings.outputs.build-output-dir }}/*.deb --clobber